wandb_version: 1

CXRBERT:
  desc: null
  value: false
MIMIC_dset:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    cli_version: 0.10.26
    code_path: code/mlp_mixer_pytorch/retrieval.py
    framework: huggingface
    huggingface_version: 4.8.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      - 11
      4: 3.8.8
      5: 0.10.26
      6: 4.8.2
      8:
      - 5
batch_size:
  desc: null
  value: 128
bert_model:
  desc: null
  value: bert-base-scratch
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.999
cuda_devices:
  desc: null
  value: null
do_test:
  desc: null
  value: false
do_train:
  desc: null
  value: true
dropout_prob:
  desc: null
  value: 0.1
embedding_size:
  desc: null
  value: 768
epochs:
  desc: null
  value: 50
eps:
  desc: null
  value: 1.0e-06
eval_during_training:
  desc: null
  value: true
eval_len_size:
  desc: null
  value: 354
gradient_accumulation_steps:
  desc: null
  value: 4
hidden_size:
  desc: null
  value: 768
i2t:
  desc: null
  value: false
img_channel:
  desc: null
  value: 1
img_embed_pool_type:
  desc: null
  value: max
img_encoder:
  desc: null
  value: full-fiber
img_hidden_sz:
  desc: null
  value: 2048
img_postion:
  desc: null
  value: true
img_size:
  desc: null
  value: 224
label_conditioned:
  desc: null
  value: true
label_conditioned_test_dataset:
  desc: null
  value: /home/data_storage/mimic-cxr/dataset/dataset/retrieval/dset/T2I_Label_Test.jsonl
label_conditioned_valid_dataset:
  desc: null
  value: /home/data_storage/mimic-cxr/dataset/dataset/retrieval/dset/T2I_Label_Valid.jsonl
load_pretrained_model:
  desc: null
  value: /home/data_storage/mimic-cxr/models/retrieval_openi/openi_base_sc_par_label
lr:
  desc: null
  value: 1.0e-05
max_seq_len:
  desc: null
  value: 512
num_image_embeds:
  desc: null
  value: 256
num_workers:
  desc: null
  value: 0
output_path:
  desc: null
  value: output/2021-12-18 04:51:39.410274
seed:
  desc: null
  value: 123
seq_len:
  desc: null
  value: 128
studyID_test_dataset:
  desc: null
  value: /home/data_storage/mimic-cxr/dataset/retrieval/openi/T2I_ID_Test_openi.jsonl
studyID_valid_dataset:
  desc: null
  value: /home/data_storage/mimic-cxr/dataset/retrieval/openi/T2I_ID_Test_openi.jsonl
t2i:
  desc: null
  value: true
train_dataset:
  desc: null
  value: /home/data_storage/mimic-cxr/dataset/image_preprocessing/Train.jsonl
vocab_size:
  desc: null
  value: 30522
warmup:
  desc: null
  value: 0.1
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.01
weight_load:
  desc: null
  value: true
with_cuda:
  desc: null
  value: true
